language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
install:
# Use clean install to ensure we're getting identical versions to package-lock.json
- npm ci
script:
# Compile the code with Gulp. This will fail the test if it doesn't compile
- npm test
